name: CI Tests

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  # Test backend
  backend-tests:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: singleclin_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore backend dependencies
        run: |
          cd packages/backend
          dotnet restore

      - name: Build backend
        run: |
          cd packages/backend
          dotnet build --no-restore

      - name: Run backend tests
        run: |
          cd packages/backend
          dotnet test --no-build --verbosity normal
        env:
          ConnectionStrings__DefaultConnection: 'Host=localhost;Database=singleclin_test;Username=postgres;Password=postgres'

  # Test frontend
  frontend-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install frontend dependencies
        run: |
          cd packages/web-admin
          npm ci

      - name: Build frontend
        run: |
          cd packages/web-admin
          npm run build

      - name: Run frontend tests (if any)
        run: |
          cd packages/web-admin
          npm run test --if-present

  # E2E tests (placeholder for future)
  e2e-tests:
    runs-on: ubuntu-latest
    needs: [backend-tests, frontend-tests]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: E2E tests placeholder
        run: |
          echo "E2E tests will be implemented later"
          echo "✅ E2E tests passed (placeholder)"
