name: CI Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  backend-tests:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: singleclin_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Restore backend dependencies
      run: |
        cd packages/backend
        dotnet restore

    - name: Build backend
      run: |
        cd packages/backend
        dotnet build --no-restore

    - name: Run backend tests
      run: |
        cd packages/backend-tests
        dotnet test --no-build --verbosity normal
      env:
        ConnectionStrings__DefaultConnection: "Host=localhost;Database=singleclin_test;Username=postgres;Password=postgres"

  frontend-tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: 'packages/web-admin/package-lock.json'

    - name: Install frontend dependencies
      run: |
        cd packages/web-admin
        npm ci

    - name: Build frontend
      run: |
        cd packages/web-admin
        npm run build

    - name: Run frontend tests (if any)
      run: |
        cd packages/web-admin
        npm run test --if-present

  e2e-tests:
    runs-on: ubuntu-latest
    needs: [backend-tests, frontend-tests]

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: singleclin_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: 'packages/web-admin/package-lock.json'

    - name: Install Playwright
      run: |
        cd packages/web-admin
        npm ci
        npx playwright install chromium

    - name: Start backend
      run: |
        cd packages/backend
        dotnet restore
        dotnet run --urls "http://localhost:5010" &
        sleep 10
      env:
        ConnectionStrings__DefaultConnection: "Host=localhost;Database=singleclin_test;Username=postgres;Password=postgres"
        ASPNETCORE_ENVIRONMENT: "Development"

    - name: Start frontend
      run: |
        cd packages/web-admin
        npm run dev &
        sleep 10

    - name: Run E2E tests
      run: |
        cd packages/web-admin
        npx playwright test --project=chromium --reporter=line
      env:
        CI: 'true'